#!/usr/bin/env python3
import csv

with open('training.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['TrainingID', 'Theme', 'Course Name', 'Instructor', 'Schedule', 'Location', 'Capacity', 'Status', 'Link to Course', 'Course Description', 'Equipment Requirements'])
    
    training_data = [
        # Theme 1: AI & Business Development (T0101-T0110)
        ("T0101", "AI & Business Development", "AI Fundamentals for AECO Professionals", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Comprehensive introduction to artificial intelligence applications in architecture, engineering, and construction. Learn machine learning basics, neural networks, and practical AI implementations for project optimization, cost estimation, and risk management.", "Laptops, AI software, case studies, datasets, Python environment"),
        ("T0102", "AI & Business Development", "Machine Learning for Construction Analytics", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Advanced machine learning techniques for analyzing construction data. Predictive modeling for project timelines, resource allocation, and quality control. Real-world case studies from major construction projects.", "Python, Jupyter notebooks, ML libraries, construction datasets, analysis tools"),
        ("T0103", "AI & Business Development", "AI-Powered Project Management Systems", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Implementing AI systems for project scheduling, budget forecasting, and resource optimization. Integration with existing project management platforms. ROI analysis and implementation strategies.", "Project management software, AI tools, integration platforms, case studies"),
        ("T0104", "AI & Business Development", "Natural Language Processing for Construction Documents", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "NLP applications for automated document analysis, contract review, and specification extraction. Reduce manual document processing time by 80%. Practical implementation using Python and NLP libraries.", "Python, NLP libraries, document samples, processing tools, case studies"),
        ("T0105", "AI & Business Development", "Computer Vision for Site Monitoring", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Computer vision technology for automated site monitoring, progress tracking, and safety compliance. Real-time analysis of construction site images and videos. Integration with drone footage and security cameras.", "Python, OpenCV, drone footage, cameras, analysis software, case studies"),
        ("T0106", "AI & Business Development", "Generative AI for Design and Planning", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Leveraging generative AI for architectural design, space planning, and construction sequencing. ChatGPT and advanced language models for design assistance. Ethical considerations and best practices.", "Generative AI tools, design software, case studies, ethical frameworks"),
        ("T0107", "AI & Business Development", "AI-Driven Cost Estimation and Budgeting", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Machine learning models for accurate cost estimation. Historical data analysis and predictive budgeting. Reducing cost overruns through AI-powered forecasting and contingency planning.", "Cost estimation software, historical data, ML tools, analysis platforms"),
        ("T0108", "AI & Business Development", "Business Development Strategy in the AI Era", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Strategic planning for AECO companies to leverage AI for competitive advantage. Market analysis, service innovation, and revenue optimization. Building AI-ready organizational culture.", "Business strategy frameworks, market analysis tools, case studies, planning software"),
        ("T0109", "AI & Business Development", "AI Ethics and Responsible Implementation", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Ethical considerations in AI deployment. Bias detection and mitigation. Regulatory compliance and responsible AI practices. Building trust with stakeholders through transparent AI implementation.", "Ethics frameworks, compliance guidelines, case studies, assessment tools"),
        ("T0110", "AI & Business Development", "AI ROI Measurement and Performance Metrics", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Measuring return on investment for AI implementations. Key performance indicators for AI projects. Cost-benefit analysis and business case development. Demonstrating value to stakeholders.", "Analytics tools, KPI frameworks, case studies, measurement software"),
        
        # Theme 2: BIM & Digital Twin (T0201-T0210)
        ("T0201", "BIM & Digital Twin", "BIM Fundamentals and Best Practices", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Comprehensive introduction to Building Information Modeling. BIM standards, workflows, and collaboration. Implementation strategies for small to large organizations. Industry standards and best practices.", "BIM software, standards documentation, case studies, collaboration tools"),
        ("T0202", "BIM & Digital Twin", "Advanced BIM Modeling Techniques", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Advanced BIM modeling for complex projects. Parametric design, family creation, and custom workflows. Optimization for performance and collaboration. Real-world project examples.", "BIM software, design tools, parametric libraries, case studies"),
        ("T0203", "BIM & Digital Twin", "BIM for Facility Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Leveraging BIM data for facility management operations. Asset tracking, maintenance scheduling, and space utilization. Integration with FM systems and IoT sensors. Lifecycle management.", "BIM software, FM systems, IoT integration, case studies, management tools"),
        ("T0204", "BIM & Digital Twin", "Digital Twin Technology and Applications", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Creating and managing digital twins of buildings and infrastructure. Real-time monitoring and simulation. Predictive maintenance and performance optimization. Integration with IoT and sensors.", "Digital twin platforms, IoT sensors, simulation software, case studies"),
        ("T0205", "BIM & Digital Twin", "BIM to Digital Twin Workflow", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Seamless transition from BIM models to operational digital twins. Data enrichment and real-time synchronization. Continuous model updates and lifecycle management. Implementation strategies.", "BIM software, digital twin platforms, integration tools, case studies"),
        ("T0206", "BIM & Digital Twin", "IFC and Open Standards in BIM", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Industry Foundation Classes (IFC) standards and open BIM workflows. Interoperability between different software platforms. Data exchange and quality assurance. Future of open standards.", "IFC tools, validation software, standards documentation, case studies"),
        ("T0207", "BIM & Digital Twin", "COBIE and Data Handover", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Construction Operations Building Information Exchange (COBie) standards. Structured data handover from design to operations. Compliance with client requirements and standards. Automated COBie generation.", "COBie tools, spreadsheet templates, validation software, case studies"),
        ("T0208", "BIM & Digital Twin", "BIM Coordination and Clash Detection", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Coordinating multi-discipline BIM models. Automated clash detection and resolution. Workflow optimization and conflict management. Reducing rework and construction delays.", "BIM software, clash detection tools, coordination platforms, case studies"),
        ("T0209", "BIM & Digital Twin", "BIM for Construction Planning and Sequencing", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "4D BIM for construction sequencing and scheduling. Visualizing construction sequences and logistics. Resource planning and site layout optimization. Improving project efficiency.", "BIM software, 4D tools, scheduling software, visualization platforms"),
        ("T0210", "BIM & Digital Twin", "BIM Governance and Standards Implementation", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Establishing BIM governance frameworks and standards. Organizational BIM strategy and implementation roadmap. Quality assurance and compliance monitoring. Building BIM maturity.", "Governance frameworks, standards documentation, implementation guides, case studies"),
        
        # Theme 3: Smart Cities & IoT (T0301-T0310)
        ("T0301", "Smart Cities & IoT", "Smart City Fundamentals and Vision", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Understanding smart city concepts and technologies. Urban challenges and technology solutions. Sustainable development and quality of life improvements. Global smart city examples and lessons learned.", "Case studies, frameworks, planning tools, documentation"),
        ("T0302", "Smart Cities & IoT", "IoT Sensors and Microcontrollers", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Introduction to IoT sensors and microcontroller platforms. Arduino, Raspberry Pi, and industrial IoT devices. Sensor selection and deployment strategies. Data collection and transmission.", "Arduino kits, sensors, microcontrollers, development boards, documentation"),
        ("T0303", "Smart Cities & IoT", "IoT Networks and Connectivity", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "IoT communication protocols and networks. WiFi, Bluetooth, LoRaWAN, and 5G for IoT. Network design and optimization. Security and reliability considerations.", "Network equipment, protocol documentation, simulation tools, case studies"),
        ("T0304", "Smart Cities & IoT", "Building Automation and Smart Buildings", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Automated building systems for energy efficiency and comfort. HVAC, lighting, and security automation. Integration with BIM and digital twins. Smart building standards and certifications.", "Building automation software, control systems, sensors, case studies"),
        ("T0305", "Smart Cities & IoT", "Smart Infrastructure and Utilities", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Smart water, energy, and waste management systems. Real-time monitoring and optimization. Reducing resource consumption and environmental impact. Integration with city-wide systems.", "Monitoring systems, control software, sensors, case studies"),
        ("T0306", "Smart Cities & IoT", "Data Analytics for Smart Cities", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Analyzing IoT data for city-wide insights. Real-time dashboards and predictive analytics. Urban planning and resource optimization. Data visualization and decision support.", "Analytics platforms, visualization tools, datasets, case studies"),
        ("T0307", "Smart Cities & IoT", "Cybersecurity for IoT and Smart Cities", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Security challenges in IoT deployments. Protecting smart city infrastructure from cyber threats. Encryption, authentication, and access control. Compliance and standards.", "Security tools, encryption software, testing platforms, case studies"),
        ("T0308", "Smart Cities & IoT", "Smart Mobility and Transportation", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Connected vehicles and autonomous transportation systems. Traffic management and congestion reduction. Integration with urban planning. Sustainability and emissions reduction.", "Mobility platforms, traffic management software, case studies"),
        ("T0309", "Smart Cities & IoT", "Citizen Engagement and Smart City Services", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Digital platforms for citizen engagement and service delivery. Mobile applications and smart city services. Community participation and feedback mechanisms. Building livable smart cities.", "Mobile platforms, engagement tools, case studies, frameworks"),
        ("T0310", "Smart Cities & IoT", "Smart City Implementation and Governance", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Planning and implementing smart city initiatives. Governance structures and stakeholder management. Funding and financing strategies. Measuring success and impact.", "Implementation frameworks, governance guides, case studies, planning tools"),
        
        # Theme 4: Industry 4.0 & Automation (T0401-T0410)
        ("T0401", "Industry 4.0 & Automation", "Industry 4.0 Fundamentals", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Understanding Industry 4.0 and digital transformation. Connected systems, data analytics, and automation. Impact on construction and manufacturing. Organizational readiness and change management.", "Case studies, frameworks, documentation, assessment tools"),
        ("T0402", "Industry 4.0 & Automation", "Robotics in Construction", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Robotic systems for construction automation. Bricklaying, concrete placement, and structural assembly robots. Safety, efficiency, and quality improvements. ROI and implementation challenges.", "Robot demonstrations, case studies, technical documentation, videos"),
        ("T0403", "Industry 4.0 & Automation", "Drones and Aerial Technology", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Drone applications in construction and surveying. Aerial photography, mapping, and inspection. Regulatory compliance and safety protocols. Integration with BIM and digital twins.", "Drone equipment, flight simulators, case studies, regulatory guides"),
        ("T0404", "Industry 4.0 & Automation", "3D Printing and Additive Manufacturing", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "3D printing technology for construction components and buildings. Material selection and structural design. Cost and time savings. Future of construction manufacturing.", "3D printers, materials, design software, case studies"),
        ("T0405", "Industry 4.0 & Automation", "Prefabrication and Modular Construction", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Off-site manufacturing and modular construction strategies. Quality control and standardization. Supply chain optimization. Reducing on-site labor and schedule.", "Manufacturing systems, case studies, design tools, documentation"),
        ("T0406", "Industry 4.0 & Automation", "Wearable Technology and Safety", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Wearable devices for worker safety and productivity. Real-time monitoring and alert systems. Health and safety compliance. Integration with site management systems.", "Wearable devices, monitoring software, case studies, safety protocols"),
        ("T0407", "Industry 4.0 & Automation", "Augmented Reality for Construction", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "AR applications for construction visualization and guidance. On-site navigation and assembly instructions. Quality control and inspection. Training and skill development.", "AR software, mobile devices, case studies, development tools"),
        ("T0408", "Industry 4.0 & Automation", "Digital Supply Chain Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Digitizing supply chain for construction materials and equipment. Real-time tracking and inventory management. Supplier integration and collaboration. Reducing waste and delays.", "Supply chain software, tracking systems, case studies, integration tools"),
        ("T0409", "Industry 4.0 & Automation", "Predictive Maintenance and Asset Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Predictive maintenance using IoT sensors and analytics. Equipment health monitoring and failure prevention. Extending asset lifespan and reducing downtime. Integration with digital twins.", "Monitoring systems, analytics software, sensors, case studies"),
        ("T0410", "Industry 4.0 & Automation", "Digital Transformation Strategy for AECO", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Developing digital transformation roadmaps for AECO companies. Technology selection and implementation planning. Organizational change and workforce development. Measuring digital maturity.", "Strategy frameworks, assessment tools, case studies, planning guides"),
        
        # Theme 5: Programming & Python (T0501-T0510)
        ("T0501", "Programming & Python", "Python Fundamentals for AECO Professionals", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Introduction to Python programming for construction and engineering applications. Variables, data types, and control structures. Practical examples and hands-on exercises. Building automation scripts.", "Python IDE, documentation, tutorials, practice exercises"),
        ("T0502", "Programming & Python", "Data Analysis with Python", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Using Python for construction data analysis. Pandas, NumPy, and data manipulation libraries. Statistical analysis and visualization. Real-world project data examples.", "Python, Jupyter, libraries, datasets, visualization tools"),
        ("T0503", "Programming & Python", "Python for BIM Automation", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Automating BIM workflows with Python. Revit API and IFC file manipulation. Batch processing and model generation. Improving productivity and reducing manual work.", "Python, BIM software APIs, documentation, case studies"),
        ("T0504", "Programming & Python", "Web Development for Construction Applications", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Building web applications for construction management. Flask and Django frameworks. Database design and integration. Deploying applications to the cloud.", "Python frameworks, web development tools, databases, hosting platforms"),
        ("T0505", "Programming & Python", "Python for IoT and Sensor Data", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Processing IoT sensor data with Python. Real-time data collection and analysis. Integration with databases and visualization tools. Building monitoring systems.", "Python, IoT libraries, sensors, databases, visualization tools"),
        ("T0506", "Programming & Python", "Machine Learning with Python", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Machine learning libraries and frameworks in Python. Scikit-learn, TensorFlow, and PyTorch. Building predictive models for construction applications. Model evaluation and optimization.", "Python, ML libraries, datasets, Jupyter notebooks, case studies"),
        ("T0507", "Programming & Python", "Python for Computational Design", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Parametric design and generative algorithms with Python. Grasshopper and Rhino integration. Creating complex geometries and design variations. Optimization and performance analysis.", "Python, Grasshopper, Rhino, design tools, case studies"),
        ("T0508", "Programming & Python", "Testing and Debugging Python Code", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Writing reliable and maintainable Python code. Unit testing and test-driven development. Debugging techniques and tools. Code quality and best practices.", "Python, testing frameworks, debugging tools, documentation"),
        ("T0509", "Programming & Python", "Python Documentation and Collaboration", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Writing clear documentation for Python projects. Code commenting and docstrings. Collaboration tools and version control. Building professional Python projects.", "Documentation tools, version control, collaboration platforms, guides"),
        ("T0510", "Programming & Python", "Advanced Python Topics", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Advanced Python concepts and patterns. Object-oriented programming and design patterns. Performance optimization and profiling. Building scalable applications.", "Python, advanced libraries, optimization tools, case studies"),
        
        # Theme 6: Computational Design (T0601-T0610)
        ("T0601", "Computational Design", "Parametric Design Fundamentals", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Introduction to parametric design and generative algorithms. Grasshopper and visual programming. Creating flexible and adaptable designs. Optimization and performance analysis.", "Grasshopper, Rhino, design tools, tutorials, case studies"),
        ("T0602", "Computational Design", "Algorithmic Thinking for Designers", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Developing algorithmic thinking and problem-solving skills. Breaking down complex design problems. Creating reusable design components. Scaling design solutions.", "Design tools, programming concepts, case studies, exercises"),
        ("T0603", "Computational Design", "Advanced Grasshopper Techniques", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Advanced Grasshopper scripting and custom components. Data trees and complex workflows. Performance optimization. Building professional design tools.", "Grasshopper, Rhino, scripting tools, documentation, case studies"),
        ("T0604", "Computational Design", "Generative Design and Optimization", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Generative design for exploring design possibilities. Multi-objective optimization. Structural and environmental performance. AI-assisted design exploration.", "Generative design software, optimization tools, case studies"),
        ("T0605", "Computational Design", "Computational Geometry and Topology", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Mathematical foundations of computational design. Geometric algorithms and transformations. Topology and spatial relationships. Advanced geometric modeling.", "Computational geometry libraries, mathematics tools, case studies"),
        ("T0606", "Computational Design", "Scripting in Design Software", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Python and C# scripting in design software. Revit API and Rhino Python. Automating design workflows. Building custom tools and plugins.", "Design software, scripting languages, APIs, documentation"),
        ("T0607", "Computational Design", "Data-Driven Design", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Using data to inform design decisions. Analyzing performance metrics and feedback. Iterative design improvement. Evidence-based design practices.", "Data analysis tools, visualization software, case studies"),
        ("T0608", "Computational Design", "Computational Fabrication", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Designing for digital fabrication and 3D printing. Optimizing designs for manufacturing constraints. Material efficiency and waste reduction. From digital to physical.", "CAM software, fabrication equipment, design tools, case studies"),
        ("T0609", "Computational Design", "Machine Learning for Design", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Applying machine learning to design problems. Training models on design data. Predictive design and pattern recognition. AI-assisted creativity.", "ML libraries, design software, datasets, case studies"),
        ("T0610", "Computational Design", "Computational Design Portfolio and Practice", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Building a computational design portfolio. Documenting design processes and results. Professional practice and business models. Advancing the field of computational design.", "Portfolio tools, documentation platforms, case studies, guides"),
        
        # Theme 7: Standards & Compliance (T0701-T0710)
        ("T0701", "Standards & Compliance", "ISO 19650 Information Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "ISO 19650 standards for information management in construction. Organizational information requirements and asset information requirements. Implementing information management systems. Compliance and auditing.", "ISO standards, documentation, implementation guides, case studies"),
        ("T0702", "Standards & Compliance", "ISO 19650 Part 1: Concepts and Principles", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Deep dive into ISO 19650-1 concepts and principles. Information management framework. Roles and responsibilities. Building information management culture.", "ISO standards, documentation, training materials, case studies"),
        ("T0703", "Standards & Compliance", "ISO 19650 Part 2: Delivery Phase", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "ISO 19650-2 for delivery phase information management. Project information requirements and execution plans. Collaborative workflows and data exchange. Quality assurance.", "ISO standards, templates, software tools, case studies"),
        ("T0704", "Standards & Compliance", "ISO 19650 Part 3: Operational Phase", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "ISO 19650-3 for operational phase information management. Asset information requirements and handover. Facility management integration. Lifecycle information management.", "ISO standards, FM systems, documentation, case studies"),
        ("T0705", "Standards & Compliance", "IFC Standards and Open BIM", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Industry Foundation Classes (IFC) standards and open BIM. Data exchange and interoperability. IFC schema and implementation. Quality assurance and validation.", "IFC tools, validation software, standards documentation, case studies"),
        ("T0706", "Standards & Compliance", "COBie Data Standards", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Construction Operations Building Information Exchange (COBie) standards. Structured data handover requirements. COBie generation and validation. Client compliance.", "COBie tools, spreadsheet templates, validation software, case studies"),
        ("T0707", "Standards & Compliance", "IDS Information Delivery Specification", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Information Delivery Specification (IDS) for defining information requirements. Creating and validating IDS documents. Ensuring data quality and completeness. Integration with BIM workflows.", "IDS tools, validation software, documentation, case studies"),
        ("T0708", "Standards & Compliance", "Building Codes and Compliance", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Building codes and regulatory compliance in design and construction. Code checking and compliance verification. Digital tools for code compliance. International standards and variations.", "Code databases, compliance software, documentation, case studies"),
        ("T0709", "Standards & Compliance", "Sustainability Standards and Certifications", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "LEED, BREEAM, and other sustainability certifications. Environmental performance standards. Measuring and reporting sustainability metrics. Green building practices.", "Certification frameworks, assessment tools, documentation, case studies"),
        ("T0710", "Standards & Compliance", "Data Privacy and Security Standards", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "GDPR, CCPA, and data privacy regulations. Protecting sensitive project and personal information. Cybersecurity standards and best practices. Compliance and audit trails.", "Privacy frameworks, security tools, documentation, case studies"),
        
        # Theme 8: Cost, Quantity & Risk Management (T0801-T0810)
        ("T0801", "Cost, Quantity & Risk", "Advanced Cost Estimation Techniques", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Mastering cost estimation from conceptual to detailed design phases. Parametric cost modeling and historical data analysis. Managing cost uncertainty and contingency planning. Real-world case studies and benchmarking.", "Cost estimation software, historical databases, analysis tools, case studies"),
        ("T0802", "Cost, Quantity & Risk", "Quantity Surveying in the Digital Age", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Modern quantity surveying practices leveraging BIM and digital tools. Automated quantity extraction and bill of quantities generation. Reducing errors and improving accuracy. Integration with cost management systems.", "BIM software, QS tools, automation platforms, case studies"),
        ("T0803", "Cost, Quantity & Risk", "Value Engineering and Cost Optimization", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Strategic value engineering to maximize project value. Identifying cost reduction opportunities without compromising quality. Life cycle costing and total cost of ownership. Stakeholder engagement and decision-making.", "VE frameworks, analysis tools, case studies, decision support software"),
        ("T0804", "Cost, Quantity & Risk", "Risk Management Framework and Strategy", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Comprehensive risk management from identification through mitigation. Risk registers and probability-impact matrices. Monte Carlo simulation for cost and schedule risk. Building organizational risk culture.", "Risk management software, simulation tools, templates, case studies"),
        ("T0805", "Cost, Quantity & Risk", "Schedule Risk and Time Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Managing schedule risk and uncertainty. Critical path analysis and schedule compression. Resource leveling and optimization. Predictive scheduling using historical data and AI.", "Scheduling software, risk analysis tools, historical data, case studies"),
        ("T0806", "Cost, Quantity & Risk", "Quality Risk and Defect Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Quality assurance and defect prevention strategies. Root cause analysis and corrective actions. Building quality culture and continuous improvement. Reducing rework and warranty costs.", "Quality management systems, inspection tools, case studies, frameworks"),
        ("T0807", "Cost, Quantity & Risk", "Financial Risk and Cash Flow Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Managing financial risks in construction projects. Cash flow forecasting and working capital management. Payment terms and contract risk allocation. Protecting profitability and financial health.", "Financial modeling software, cash flow tools, contract templates, case studies"),
        ("T0808", "Cost, Quantity & Risk", "Insurance and Liability Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Understanding insurance requirements and coverage. Managing liability and claims. Professional indemnity and project insurance. Risk transfer strategies and cost implications.", "Insurance frameworks, contract templates, case studies, legal guidance"),
        ("T0809", "Cost, Quantity & Risk", "Earned Value Management", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Earned value management for integrated cost and schedule control. Performance measurement and variance analysis. Forecasting final costs and completion dates. Stakeholder reporting and transparency.", "EVM software, project management tools, templates, case studies"),
        ("T0810", "Cost, Quantity & Risk", "Contingency Planning and Resilience", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Building resilient projects through contingency planning. Scenario analysis and stress testing. Adaptive management and flexibility. Learning from disruptions and building organizational resilience.", "Scenario planning tools, simulation software, case studies, frameworks"),
        
        # Theme 9: Resource Management & Entrepreneurship (T0901-T0910)
        ("T0901", "Resource Management & Entrepreneurship", "Strategic Resource Planning", "Industry Expert", "TBD", "TBD", "TBD", "Active", "TBD", "Optimizing resource allocation across multiple projects. Capacity planning and workforce forecasting. Skills matrix and competency development. Building high-performing teams.", "Resource management software, planning tools, case studies, frameworks